AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Lambda Layer containing a Python module that enables AWS Lambda
  functions to maintain state and persist data between invocations by writing
  to a dict-like variable. It achieves this by using the DynamoDB free tier and
  so it can be used without adding any costs to your project.
Metadata:
  Source: https://github.com/gene1wood/aws-lambda-persistence
Resources:
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11
        - python3.12
        - python3.13
        - python3.14
      Content:
        S3Bucket: aws-lambda-persistence-layer
        S3Key: layer.zip
      Description: A Python module that enables AWS Lambda functions to maintain
        state and persist data between invocations by writing to a dict-like
        variable. It achieves this by using the DynamoDB free tier and so it
        can be used without adding any costs to your project.
      LayerName: aws-lambda-persistence
      LicenseInfo: GPL-3.0-or-later
  LambdaLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LambdaLayer
      Principal: '*'  # Allow usage from any AWS account
Outputs:
  LayerArn:
    Value: !Ref LambdaLayer